### ISSUE TITLE
Stack issues

### ISSUE THREAD

**Issue by PTDreamer** [admiralmaggie/stm32f3_lvgl#1]
https://github.com/admiralmaggie/stm32f3_lvgl/blob/3bb3574b41d323cc63ff18adffd8c868da8e5144/Core/Src/freertos.c#L61
https://github.com/admiralmaggie/stm32f3_lvgl/blob/3bb3574b41d323cc63ff18adffd8c868da8e5144/Core/Src/freertos.c#L55

Seems you are not defining a stack size for the tasks

**Comment by admiralmaggie** [comment]
That was it! Thanks!
